version: '2'
services:

  spring-es-mongodb:
    environment:
      MONGODB_PASSWORD: mongo_password
    build: ./docker/mongodb
    ports:
      - 27017:27017
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  spring-es-elasticsearchdb:
    environment:
      ES_CLUSTER_NAME: spring-es-sample
      ES_NETWORK_HOST: 0.0.0.0
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms256m -Xmx256m
    build: ./docker/elasticsearchdb
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  spring-es-sample-application:
    environment:
      MONGODB_PASSWORD: mongo_password
    build: .
    depends_on:
      - spring-es-mongodb
      - spring-es-elasticsearchdb
    ports:
      - 8080:8080
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  esdata1:
    driver: local